
export const LIST_FOLDER = 'LIST_FOLDER';
export const ADD_FOLDER = 'ADD_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const EDIT_FOLDER = 'EDIT_FOLDER';
export const SET_CREATE_FOLDER_MODE = 'SET_CREATE_FOLDER_MODE';
export const LIST_MANAGER2FOLDERS = 'LIST_MANAGER2FOLDERS';
export const LIST_USER2FOLDERS = 'LIST_USER2FOLDERS';
export const SET_SELECTED_FOLDER = 'SET_SELECTED_FOLDER';