
export const LIST_REPORT = 'LIST_REPORT';
export const LIST_REPORT_BY_FORM = 'LIST_REPORT_BY_FORM';
export const ADD_REPORT = 'ADD_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const DELETE_REPORT_BY_FORM = 'DELETE_REPORT_BY_FORM';
export const EDIT_REPORT = 'EDIT_REPORT';
export const SET_SELECTED_FORM_DATA = 'SET_SELECTED_REPORT_DATA';
export const SET_CREATE_REPORT_MODE = 'SET_CREATE_REPORT_MODE';