export const api_list = {
    signIn: 'signin/signin',
    register: 'signin/register',
    signOut: 'signin/signout',
    formList: 'forms/list',
    formAdd: 'forms/add',
    formEdit: 'forms/edit',
    formDelete: 'forms/delete',
    reportList: 'reports/list',
    reportListByForm: 'reports/listByForm',
    reportAdd: 'reports/add',
    reportEdit: 'reports/edit',
    reportDelete: 'reports/delete',
    reportDeleteByForm: 'reports/deleteByForm',
    folderList: 'folders/list',
    folderAdd: 'folders/add',
    folderEdit: 'folders/edit',
    folderDelete: 'folders/delete',
    userList: 'folders/userList',
};
